
name: hehe

on:
  push:
    branches:
    - main
  
  schedule:
  - cron: "0 1/2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set global directory
        run: git config --global --add safe.directory /github/workspace
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 1
      
      - name: update
        run: |
          cat > hehe
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > hehe
      
      - name: commit 
        run: |
          git config --local user.email "fawwazthoerif@gmail.com"
          git config --local user.name "akasakaid"
          git add -A
          git commit -am "hehe"
      
      - name: push
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
